## replace LLVMROOT and LLVMGCC as appropriate
NETID = `okur2`
LLVMROOT = /Users/semih/code/llvm
LLVMGCC = clang
LLVMAS  = $(LLVMROOT)/Debug+Asserts/bin/llvm-as
LLVMDIS = $(LLVMROOT)/Debug+Asserts/bin/llvm-dis
LLVMOPT = $(LLVMROOT)/Debug+Asserts/bin/opt

## change library name appropriately for your system
DYLIB   = /Users/semih/code/llvm-pass/acc-project/Debug+Asserts/lib/MP1.dylib