##===- projects/sample/lib/sample/Makefile -----------------*- Makefile -*-===##

#
# Indicate where we are relative to the top of the source tree.
#
LEVEL=..

#
# Give the name of a library.  Build a dynamically loadable version.
#
LIBRARYNAME=MP1
SHARED_LIBRARY=1
LOADABLE_MODULE=1
BUILD_ARCHIVE=1

#
# Include Makefile.common so we know what to do.
#
include $(LEVEL)/Makefile.common

